name: Backend Pipeline

on:
  workflow_dispatch:
  push:
    branches:
    - main
env:
  REPOSITORY: dvn-workshop/production/backend
  IMAGE_TAG: ${{ github.sha }}
  
permissions:
  contents: read
  id-token: write

jobs:
  backend:
    name: Backend Job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-region: ${{ vars.AWS_REGION }}
        role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}

      run: |
        docker build -f ./apps/backend/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG ./apps/backend/
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
    
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        repository: workshopCloud-gitops
        token: ${{ secrets.PAT }}

    - name: Kustomize Edit
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}

      run: |
        kustomize edit set image $REGISTRY/$REPOSITORY=$REGISTRY/$REPOSITORY:$IMAGE_TAG 
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add ./workshopCloud-gitops/manifests/kustomization.yml
        git commit -m "[BOT] Updating image to $REGISTRY/$REPOSITORY:$IMAGE_TAG"
        git push
