name: Backend Pipeline

on:
  workflow_dispatch:
  push:
    branches:
    - main
env:
  REPOSITORY: dvn-workshop/production/backend
  IMAGE_TAG: ${{ github.sha }}

jobs:
  backend:
    name: Backend Job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5.1.0
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push docker image to Amazon ECR
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}

      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
